# Dependencies
markdown:         kramdown
highlighter:      pygments

# Paginate
gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "/page/:num"

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# 软件开发，前端开发，自动化构建，Java, JavaScript, TypeScript, Angular, React, Vue

# Setup
title:            '小平'
tagline:          '专注于优秀的软件开发技术，用先进的技术解放生产力'
description:      '专注于优秀的软件开发技术，用先进的技术解放生产力'
url:              http://xiaoping0x.github.io
baseurl:          /

author:
  name:           xiaoping0x
  url:            http://xiaoping0x.github.io

# Custom vars
version:          2.1.0

github:
  url:            http://xiaoping0x.github.io

social:
  github:         http://xiaoping0x.github.io

track:
  cnzz:           123456 # place the cnzz tracking id, ref:cnzz.com | <http://www.umeng.com/>

comment:
  disqus:         abc1234567890 # place the disqus shorname for your custom domain

sass:
  style: compressed
